version: 5.0.1
branches:
  only:
  - master
pull_requests:
  do_not_increment_build_number: true
install:
- ps: .\build\install.ps1
build_script:
- ps: .\build\build.ps1 $env:APPVEYOR_BUILD_VERSION $env:APPVEYOR_REPO_TAG_NAME
test_script:
- ps: .\build\test.ps1
artifacts:
- path: '**\*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: YOUR_SECURE_TOKEN_FOR_NUGET
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
      branch: master                # release from master branch only
      appveyor_repo_tag: true       # deploy on tag push only
